feat: 🚀 search screen
isadorapda/books-library pull request #5
Opened 2022-09-28 15:28 UTC by isadorapda

Improved styling. Replaced excessive ternary conditional with functions.

2022-09-29 07:36 UTC, brunopascottini requested changes

2022-09-29 07:36 UTC, brunopascottini commented on src/screens/Search.tsx
> +const LoadinBook = styled.div`
Typo

2022-09-29 07:36 UTC, brunopascottini commented on src/components/BookCard.tsx
> +  }
For animations, I think you can have a better visual effect by ending it in the same point that it started.

2022-09-29 07:36 UTC, brunopascottini commented on src/components/BookCard.tsx
> +  }
Same comments for animations

2022-09-29 07:36 UTC, brunopascottini commented on src/components/BookCard.tsx
> +  const subjectsToShow = () => {
Could you type this function?

2022-09-29 07:36 UTC, brunopascottini commented on src/components/BookCard.tsx
> +    return subjectsArray.map((sub) => <li key={sub}>{sub}</li>)
```
if (!subjectsArray) {
      return []
    }
return subjectsArray.slice(0, 10).map((sub) => <li key={sub}>{sub}</li>)
```

If the second parameter of slice is bigger than the array length it will not throw errors, you could remove one if condition.

2022-09-29 07:36 UTC, brunopascottini commented on src/screens/Search.tsx
> +      {isLoading || (isLoading && data) ? (
This boolean logic could be simplified. Think about the second isLoading of this line and it's impact with the logical operators

2022-09-29 08:27 UTC, isadorapda commented on src/components/BookCard.tsx
> +    return subjectsArray.map((sub) => <li key={sub}>{sub}</li>)
However, when it is smaller it throws errors.

2022-09-29 08:44 UTC, isadorapda commented on src/components/BookCard.tsx
> +    return subjectsArray.map((sub) => <li key={sub}>{sub}</li>)
You were right! Tks

2022-10-01 11:32 UTC, brunopascottini requested changes

2022-10-01 11:32 UTC, brunopascottini commented on src/screens/Search.tsx
> +  }};
This is going to work but there are better ways of doing this. One thing to notice is that a switch with a single 'case' could be easily replaced by an if or a ternary operator. Also the color property is the same in both scenarios. I'll be in touch to explain other alternatives.

2022-10-01 11:32 UTC, brunopascottini commented on src/screens/Search.tsx
> +  const [searchTerm, setSearchTerm] = React.useState<string>('harry')
I think this is used for development and should not be here.

2022-10-01 11:32 UTC, brunopascottini commented on src/screens/Search.tsx
> +  const resultSearch = () => {
Suggestion:
```
const getSearchResultLabel = () => {
```

2022-10-01 11:32 UTC, brunopascottini commented on src/screens/Search.tsx
> +      <h2>Type keywords in the search input to find your next book!</h2>
Just a reminder that this message is for the user and we can't assume that they know what a search input is.

2022-10-01 11:32 UTC, brunopascottini commented on src/components/NavigationBar.tsx
> +          fill="#94B49F"
I missed this in my previous reviews. The svg file could be in a separate folder as icons or images and you could just import and use it in the JSX. The component would look cleaner this way

2022-10-05 07:58 UTC, brunopascottini approved these changes

2022-10-05 10:04 UTC, merged